config/routes.rb
Rails.application.routes.draw do
  get 'users/index' => 'users#index'
  get "users/show/:name" => 'users#show'
  resources :stores
  devise_for :users
  root 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader

  with_options presence: true do
    validates :name
    validates :body
    validates :address
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  mount_uploader :image, ImageUploader
  validates :username, presence: true
  has_many :stores, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_sign_up_params, only: [:create], if: :devise_controller?
  before_action :configure_account_update_params, only: [:update], if: :devise_controller?
  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :image])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :image])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    if user_signed_in?
      redirect_to stores_path
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    @store.user_id = current_user.id
    if @store.save
      redirect_to store_path(@store), notice: "投稿しました"
    else
      render :new
    end
  end

  def edit
    @store = Store.find(params[:id])
    if @store.user != current_user
      redirect_to store_path, alert: "不正なアクセスです"
    end
  end

  def update
    @store = Store.find(params[:id])
    if @store.update(store_params)
      redirect_to store_path(@store), notice: "更新しました"
    else
      render :edit
    end
  end

  def destroy
    store = Store.find(params[:id])
    if store.user == current_user
      store.destroy
      redirect_to store_path
    else
      redirect_to store_path, alert: "不正なアクセスです"
    end
  end

  private
  def store_params
    params.require(:store).permit(:name, :body, :address, :image)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end


  # protected

  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  # end

  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(username: params[:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title="")
    base_title = "Search Coffee Stand"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<% provide(:title, 'Home')%>
<div class="top">
  <div class="shadow">
    <div class="text-center title">
      <h1>Search Coffee Stand</h1>
      <p>Search your favorite Coffee Stand</p>
      <%= link_to  "SIGNUP", new_user_registration_path, class: "text-secondary mx-2" %>
      <%= link_to  "LOGIN", new_user_session_path, class: "text-secondary mx-2" %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <%= link_to  "RailsApp", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to  "投稿一覧",  stores_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to  "logout",  destroy_user_session_path, method: :delete, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to  "#{current_user.username}",  "/users/#{current_user.username}", class: "nav-link" %>
        </li>
        
      <% else %>
        <li class="nav-item">
          <%= link_to  "Signup",  new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to  "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="main">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% elsif alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stores/_errors.html.erb
<% if store.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(store.errors.count, "error") %></h4>
    <p><%= pluralize(store.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
  </div>
  <hr>
  <p class="mb-0">
    <% store.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </p>
<% end %>

app/views/stores/_form.html.erb
<%= form_for @store do |f| %>
  <div class="form-group">
    <label>Store name</label>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <label>Address</label>
    <%= f.text_field :address, class:"form-control" %>
  </div>

  <div class="form-group">
    <label>Content</label>
    <%= f.text_field :body, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br/>
    <%= f.file_field :image %>
  </div>

  <div>
    <%= f.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>修正画面</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/stores/index.html.erb
<div class="container mt-5">
  <div class="row">
    <% @stores.each do |store|%>
      <div class="col-lg-4 col-md-12 mb-4">
        <div class="card">
          <% if store.image.present? %>
            <%= image_tag store.image.url %>
          <% else %>
            <%= image_tag 'no-photo.jpg'%>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= store.name %></h5>
            <p class="card-text"><%= store.address %></p>
            <% if user_signed_in? %>
              <%= link_to  "edit", edit_store_path(store), class: "btn btn-primary" %>
              <%= link_to  "delete", store_path(store), class: "btn btn-danger", method: :delete %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
    <%= link_to  "create", new_store_path, class: "btn btn-success" %>
</div>

app/views/stores/new.html.erb
<%= render 'errors', store: @store %>
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>新規投稿</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>  

app/views/stores/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= @store.name %></h5>
          <p class="card-text"><%= @store.body %></p>
          <p class="card-text"><%= @store.address %></p>
          <p class="card-text">
            <small class="text-muted">更新日：<%= @store.updated_at %></small>
          </p>
          <% if @store.user == current_user %>
            <%= link_to  "編集", edit_store_path, class: "btn btn-success" %>
            <%= link_to  "削除", store_path(@store),method: :delete, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <h1>about me</h1>
  <%= image_tag @user.image.url %>
  <h3>ユーザー名</h3>
  <p><%= @user.username %></p>
  <% if @user == current_user %>
    <h3>メールアドレス</h3>
    <p><%= @user.email %></p>
    <%= link_to  "編集", edit_user_registration_path, class: "btn btn-primary" %>
  <% end %>
</div>